<Project Sdk="Microsoft.NET.Sdk">
  <!-- Polecat configuration, projections and queries. -->
  <ItemGroup>
    <InternalsVisibleTo Include="PokerEventSourced.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polecat" Version="5.31.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokerEventSourced.Domain\PokerEventSourced.Domain.csproj" />
  </ItemGroup>
</Project>
